In [2]:
import pandas as pd

In [3]:
filepath = "../telemetria.csv"
data_raw = pd.read_csv(filepath)

In [4]:
data_raw.head()

,tracking_id,vehicle_id,company_id,route_id,driver_id,event_time,received_at,latitude,longitude,speed,fuel_level,battery_level,odometer_km,passenger_count,event_type
0,61781b27-58b5-49a1-a4b9-a5365b98e050,VEH_0003,EMP_003,RUTA_007,EMP_003_DRV_048,2024-03-04 13:08:26,2024-03-04 13:08:32,2.620703,-74.338697,19.98,72.28,81.14,78234.21,25.0,P20
1,427e574c-1d4b-440f-bb0b-d06d84200bf0,VEH_0028,EMP_003,RUTA_018,EMP_003_DRV_037,2024-03-05 18:07:20,2024-03-05 18:07:24,9.252828,-75.637242,28.05,79.58,82.84,44825.01,41.0,P20
2,dcbd2c8a-3b4d-429a-8af1-352f964c53f4,VEH_0156,EMP_001,RUTA_007,EMP_001_DRV_067,2024-03-04 18:05:01,2024-03-04 18:05:05,2.888177,-73.223336,30.59,80.87,75.87,19427.25,NaN,TR10
3,e883266c-e209-4280-96d1-bb4079754c17,VEH_0035,EMP_005,RUTA_010,EMP_005_DRV_079,2024-03-05 15:36:09,2024-03-05 15:36:15,9.828977,-75.514760,65.75,66.67,92.99,35270.85,NaN,T30
4,80df3b8f-896f-4def-a64d-c476d47ea7e0,VEH_0237,EMP_002,RUTA_013,EMP_002_DRV_052,2024-03-05 01:55:45,2024-03-05 01:55:51,4.358705,-74.397611,57.48,37.75,84.32,17255.92,NaN,TR10

In [15]:
# Analize nulls
print(data_raw.isna().sum())

tracking_id             0
vehicle_id           1250
company_id              0
route_id                0
driver_id               0
event_time           1250
received_at             0
latitude             1250
longitude            1250
speed                   0
fuel_level              0
battery_level           0
odometer_km             0
passenger_count    202759
event_type              0
dtype: int64

In [18]:
# Print all data types
print(data_raw.dtypes)

tracking_id         object
vehicle_id          object
company_id          object
route_id            object
driver_id           object
event_time          object
received_at         object
latitude           float64
longitude          float64
speed              float64
fuel_level         float64
battery_level      float64
odometer_km        float64
passenger_count    float64
event_type          object
dtype: object

In [31]:
# Analize duplicates
# Shows all copies of duplicate rows
duplicate_rows = data_raw[data_raw.duplicated(subset=['tracking_id', 'vehicle_id', 'event_time', 'event_type'], keep=False)]
duplicate_rows.head()

,tracking_id,vehicle_id,company_id,route_id,driver_id,event_time,received_at,latitude,longitude,speed,fuel_level,battery_level,odometer_km,passenger_count,event_type
21,09d9a76f-d854-4555-851d-83a4de4a30a3,VEH_0117,EMP_002,RUTA_019,EMP_002_DRV_025,2024-03-04 14:24:43,2024-03-04 14:25:42,8.562770,-73.390917,32.28,78.30,92.99,44265.77,NaN,T30
33,bf60a268-d027-4919-aa8a-4bf0dad73b57,VEH_0180,EMP_005,RUTA_040,EMP_005_DRV_018,2024-03-06 01:02:47,2024-03-06 01:32:47,6.800084,-75.239284,23.07,53.56,88.08,8934.83,NaN,T30
145,e2274cb0-1e32-440c-b325-7529108f6df6,VEH_0211,EMP_001,RUTA_032,EMP_001_DRV_026,2024-03-04 21:57:34,2024-03-04 21:59:25,7.711067,-75.424013,12.17,80.32,95.26,43307.79,13.0,P20
167,d6806ec3-331e-405b-a0a8-1042f5af94de,VEH_0217,EMP_002,RUTA_006,EMP_002_DRV_017,2024-03-04 17:07:17,2024-03-04 16:31:17,4.362430,-76.000481,200.00,69.48,86.72,74085.53,NaN,T30
172,d845eb42-3a61-41e1-a8f1-0210c0543ecb,VEH_0159,EMP_004,RUTA_025,EMP_004_DRV_036,2024-03-06 00:25:44,2024-03-06 00:28:26,10.327604,-73.867406,26.10,43.01,70.39,62770.18,NaN,TR10

In [32]:
len(duplicate_rows)

7368

In [25]:
# Analize events out of range (event_time > received_at)
outside_time = data_raw[data_raw['event_time'] > data_raw['received_at']]
outside_time.head()

,tracking_id,vehicle_id,company_id,route_id,driver_id,event_time,received_at,latitude,longitude,speed,fuel_level,battery_level,odometer_km,passenger_count,event_type
165,fdd153bd-55a1-417b-89f6-e76f1bf37fbc,VEH_0087,EMP_002,RUTA_035,EMP_002_DRV_003,2024-03-05 12:20:30,2024-03-05 11:39:30,3.094907,-73.611575,29.92,62.79,88.00,71538.95,NaN,TR10
167,d6806ec3-331e-405b-a0a8-1042f5af94de,VEH_0217,EMP_002,RUTA_006,EMP_002_DRV_017,2024-03-04 17:07:17,2024-03-04 16:31:17,4.362430,-76.000481,200.00,69.48,86.72,74085.53,NaN,T30
247,a8a1a004-7f79-417d-a8e5-c4fbcadbabc4,VEH_0094,EMP_004,RUTA_019,EMP_004_DRV_038,2024-03-06 00:50:27,2024-03-05 23:54:27,10.303306,-73.072462,45.55,65.06,97.90,42145.56,6.0,P20
292,e0819787-b236-4146-8538-f5f75aad6d25,VEH_0033,EMP_003,RUTA_037,EMP_003_DRV_077,2024-03-05 11:18:24,2024-03-05 10:37:24,7.849807,-73.527167,38.73,67.98,84.69,12401.17,NaN,T30
301,74194ba7-c786-4559-a2c1-a4d10ccba7d0,VEH_0072,EMP_002,RUTA_018,EMP_002_DRV_002,2024-03-04 08:23:24,2024-03-04 07:34:24,7.640372,-75.810033,33.01,59.61,91.36,43974.06,50.0,P20

In [26]:
len(outside_time)

4852

In [28]:
# Analyze invalid coordinates
invalid_coordinates = data_raw[
    (data_raw['latitude'] < -90) | (data_raw['latitude'] > 90) |
    (data_raw['longitude'] < -180) | (data_raw['longitude'] > 180)
]

invalid_coordinates.head()

,tracking_id,vehicle_id,company_id,route_id,driver_id,event_time,received_at,latitude,longitude,speed,fuel_level,battery_level,odometer_km,passenger_count,event_type
83,53ec2276-2279-40c9-8784-f7cb975073aa,VEH_0180,EMP_005,RUTA_040,EMP_005_DRV_070,2024-03-06 08:14:38,2024-03-06 08:14:43,200.000000,-75.225749,36.15,91.00,81.74,8969.84,NaN,TR10
461,f4589aa3-5046-419e-b288-8024426c9ac8,VEH_0179,EMP_004,RUTA_016,EMP_004_DRV_067,2024-03-06 09:38:17,2024-03-06 09:38:23,6.354395,300.000000,44.62,90.82,70.09,67194.37,NaN,TR10
503,c89cea9d-2d30-4602-9a09-830310a8d36b,VEH_0059,EMP_004,RUTA_031,EMP_004_DRV_032,2024-03-05 10:57:23,2024-03-05 10:57:28,95.000000,-73.352560,57.55,74.38,83.67,45877.09,NaN,TR10
509,3afb2886-d642-46b3-89b6-3bb97fe9705f,VEH_0130,EMP_005,RUTA_036,EMP_005_DRV_076,2024-03-05 13:29:25,2024-03-05 13:29:26,-95.000000,-73.861080,25.00,83.60,94.54,65191.81,NaN,TR10
870,0e3dcf2d-0bff-4091-8ea0-2facd6707193,VEH_0027,EMP_002,RUTA_030,EMP_002_DRV_025,2024-03-04 15:53:35,2024-03-04 15:53:40,200.000000,-74.545406,34.64,44.07,89.61,7487.87,NaN,T30

In [27]:
len(invalid_coordinates)

2484

In [29]:
# Analyze imposible speed
imposible_speed = data_raw[
    (data_raw['speed'] < 0) | (data_raw['speed'] > 150)
]

imposible_speed.head()

,tracking_id,vehicle_id,company_id,route_id,driver_id,event_time,received_at,latitude,longitude,speed,fuel_level,battery_level,odometer_km,passenger_count,event_type
79,2d505eb6-523f-43d7-b36b-b8db86bc9065,VEH_0175,EMP_005,RUTA_040,EMP_005_DRV_058,2024-03-04 23:32:11,2024-03-04 23:32:14,7.049148,-73.228448,320.0,33.17,89.79,23073.61,NaN,T30
167,d6806ec3-331e-405b-a0a8-1042f5af94de,VEH_0217,EMP_002,RUTA_006,EMP_002_DRV_017,2024-03-04 17:07:17,2024-03-04 16:31:17,4.362430,-76.000481,200.0,69.48,86.72,74085.53,NaN,T30
773,08da269e-6be6-4aa1-a125-c73b68af8103,VEH_0178,EMP_003,RUTA_002,EMP_003_DRV_049,2024-03-05 01:23:48,2024-03-05 01:23:49,5.118087,-75.292002,160.0,46.88,96.06,29412.80,NaN,TR10
992,c816d704-a6a0-4e34-94d8-0a9f25fac9e5,VEH_0025,EMP_005,RUTA_018,EMP_005_DRV_074,2024-03-05 22:27:05,2024-03-05 22:27:06,4.896591,-75.745477,200.0,75.27,90.00,28089.23,NaN,T30
1101,eeb313e2-ab76-4854-8a49-c6a6fd463ba6,VEH_0150,EMP_005,RUTA_018,EMP_005_DRV_055,2024-03-05 17:23:55,2024-03-05 17:24:03,6.789343,-75.755147,160.0,78.41,76.55,44855.90,NaN,TR10

In [30]:
len(imposible_speed)

2000