In [36]:
import polars as pl
import matplotlib.pyplot as plt

In [37]:
filepath = "../telemetria.csv"
data_raw = pl.read_csv(filepath, try_parse_dates=True)

In [38]:
print(f"Dimensions: {data_raw.shape}")
data_raw.head()

Dimensions: (253750, 15)

shape: (5, 15)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tracking_ ┆ vehicle_i ┆ company_i ┆ route_id ┆ … ┆ battery_l ┆ odometer_ ┆ passenger ┆ event_typ │
│ id        ┆ d         ┆ d         ┆ ---      ┆   ┆ evel      ┆ km        ┆ _count    ┆ e         │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 61781b27- ┆ VEH_0003  ┆ EMP_003   ┆ RUTA_007 ┆ … ┆ 81.14     ┆ 78234.21  ┆ 25.0      ┆ P20       │
│ 58b5-49a1 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a4b9-a53 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 65b…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 427e574c- ┆ VEH_0028  ┆ EMP_003   ┆ RUTA_018 ┆ … ┆ 82.84     ┆ 44825.01  ┆ 41.0      ┆ P20       │
│ 1d4b-440f ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -bb0b-d06 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ d84…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ dcbd2c8a- ┆ VEH_0156  ┆ EMP_001   ┆ RUTA_007 ┆ … ┆ 75.87     ┆ 19427.25  ┆ null      ┆ TR10      │
│ 3b4d-429a ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -8af1-352 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ f96…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ e883266c- ┆ VEH_0035  ┆ EMP_005   ┆ RUTA_010 ┆ … ┆ 92.99     ┆ 35270.85  ┆ null      ┆ T30       │
│ e209-4280 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -96d1-bb4 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 079…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 80df3b8f- ┆ VEH_0237  ┆ EMP_002   ┆ RUTA_013 ┆ … ┆ 84.32     ┆ 17255.92  ┆ null      ┆ TR10      │
│ 896f-4def ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a64d-c47 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 6d4…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [39]:
null_counts = data_raw.null_count()
null_counts

shape: (1, 15)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tracking_ ┆ vehicle_i ┆ company_i ┆ route_id ┆ … ┆ battery_l ┆ odometer_ ┆ passenger ┆ event_typ │
│ id        ┆ d         ┆ d         ┆ ---      ┆   ┆ evel      ┆ km        ┆ _count    ┆ e         │
│ ---       ┆ ---       ┆ ---       ┆ u32      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ u32       ┆ u32       ┆ u32       ┆          ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0         ┆ 1250      ┆ 0         ┆ 0        ┆ … ┆ 0         ┆ 0         ┆ 202759    ┆ 0         │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [40]:
data_raw.select(["speed", "fuel_level", "battery_level", "odometer_km"]).describe()

shape: (9, 5)
┌────────────┬───────────┬────────────┬───────────────┬──────────────┐
│ statistic  ┆ speed     ┆ fuel_level ┆ battery_level ┆ odometer_km  │
│ ---        ┆ ---       ┆ ---        ┆ ---           ┆ ---          │
│ str        ┆ f64       ┆ f64        ┆ f64           ┆ f64          │
╞════════════╪═══════════╪════════════╪═══════════════╪══════════════╡
│ count      ┆ 253750.0  ┆ 253750.0   ┆ 253750.0      ┆ 253750.0     │
│ null_count ┆ 0.0       ┆ 0.0        ┆ 0.0           ┆ 0.0          │
│ mean       ┆ 40.115612 ┆ 65.495955  ┆ 84.979306     ┆ 43304.807609 │
│ std        ┆ 27.88731  ┆ 16.510312  ┆ 8.671745      ┆ 21675.218098 │
│ min        ┆ 0.11      ┆ 18.95      ┆ 70.0          ┆ 0.0          │
│ 25%        ┆ 26.49     ┆ 54.57      ┆ 77.44         ┆ 25901.73     │
│ 50%        ┆ 37.65     ┆ 66.78      ┆ 84.98         ┆ 42345.52     │
│ 75%        ┆ 50.23     ┆ 77.9       ┆ 92.5          ┆ 62331.3      │
│ max        ┆ 450.0     ┆ 99.87      ┆ 100.0         ┆ 80339.35     │
└────────────┴───────────┴────────────┴───────────────┴──────────────┘

In [41]:
duplicate_rows = data_raw.filter(
    pl.struct(["tracking_id", "vehicle_id", "event_time", "event_type"]).is_duplicated()
)

print(f"Dimensions: {duplicate_rows.shape}")
duplicate_rows.head()

Dimensions: (7368, 15)

shape: (5, 15)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tracking_ ┆ vehicle_i ┆ company_i ┆ route_id ┆ … ┆ battery_l ┆ odometer_ ┆ passenger ┆ event_typ │
│ id        ┆ d         ┆ d         ┆ ---      ┆   ┆ evel      ┆ km        ┆ _count    ┆ e         │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 09d9a76f- ┆ VEH_0117  ┆ EMP_002   ┆ RUTA_019 ┆ … ┆ 92.99     ┆ 44265.77  ┆ null      ┆ T30       │
│ d854-4555 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -851d-83a ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 4de…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ bf60a268- ┆ VEH_0180  ┆ EMP_005   ┆ RUTA_040 ┆ … ┆ 88.08     ┆ 8934.83   ┆ null      ┆ T30       │
│ d027-4919 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -aa8a-4bf ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0da…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ e2274cb0- ┆ VEH_0211  ┆ EMP_001   ┆ RUTA_032 ┆ … ┆ 95.26     ┆ 43307.79  ┆ 13.0      ┆ P20       │
│ 1e32-440c ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -b325-752 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 910…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ d6806ec3- ┆ VEH_0217  ┆ EMP_002   ┆ RUTA_006 ┆ … ┆ 86.72     ┆ 74085.53  ┆ null      ┆ T30       │
│ 331e-405b ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a0a8-104 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2f5…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ d845eb42- ┆ VEH_0159  ┆ EMP_004   ┆ RUTA_025 ┆ … ┆ 70.39     ┆ 62770.18  ┆ null      ┆ TR10      │
│ 3a61-41e1 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a8f1-021 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0c0…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
outside_time = data_raw.filter(pl.col("event_time") > pl.col("received_at"))
print(f"Dimensions: {outside_time.shape}")
outside_time.head()

Dimensions: (4852, 15)

shape: (5, 15)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tracking_ ┆ vehicle_i ┆ company_i ┆ route_id ┆ … ┆ battery_l ┆ odometer_ ┆ passenger ┆ event_typ │
│ id        ┆ d         ┆ d         ┆ ---      ┆   ┆ evel      ┆ km        ┆ _count    ┆ e         │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ fdd153bd- ┆ VEH_0087  ┆ EMP_002   ┆ RUTA_035 ┆ … ┆ 88.0      ┆ 71538.95  ┆ null      ┆ TR10      │
│ 55a1-417b ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -89f6-e76 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ f1b…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ d6806ec3- ┆ VEH_0217  ┆ EMP_002   ┆ RUTA_006 ┆ … ┆ 86.72     ┆ 74085.53  ┆ null      ┆ T30       │
│ 331e-405b ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a0a8-104 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2f5…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ a8a1a004- ┆ VEH_0094  ┆ EMP_004   ┆ RUTA_019 ┆ … ┆ 97.9      ┆ 42145.56  ┆ 6.0       ┆ P20       │
│ 7f79-417d ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a8e5-c4f ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ bca…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ e0819787- ┆ VEH_0033  ┆ EMP_003   ┆ RUTA_037 ┆ … ┆ 84.69     ┆ 12401.17  ┆ null      ┆ T30       │
│ b236-4146 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -8538-f5f ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 75a…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 74194ba7- ┆ VEH_0072  ┆ EMP_002   ┆ RUTA_018 ┆ … ┆ 91.36     ┆ 43974.06  ┆ 50.0      ┆ P20       │
│ c786-4559 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a2c1-a4d ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 10c…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [43]:
invalid_coordinates = data_raw.filter(
    (pl.col("latitude") < -90) | (pl.col("latitude") > 90) |
    (pl.col("longitude") < -180) | (pl.col("longitude") > 180)
)
print(f"Dimensions: {invalid_coordinates.shape}")
invalid_coordinates.head()

Dimensions: (2484, 15)

shape: (5, 15)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tracking_ ┆ vehicle_i ┆ company_i ┆ route_id ┆ … ┆ battery_l ┆ odometer_ ┆ passenger ┆ event_typ │
│ id        ┆ d         ┆ d         ┆ ---      ┆   ┆ evel      ┆ km        ┆ _count    ┆ e         │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 53ec2276- ┆ VEH_0180  ┆ EMP_005   ┆ RUTA_040 ┆ … ┆ 81.74     ┆ 8969.84   ┆ null      ┆ TR10      │
│ 2279-40c9 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -8784-f7c ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ b97…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ f4589aa3- ┆ VEH_0179  ┆ EMP_004   ┆ RUTA_016 ┆ … ┆ 70.09     ┆ 67194.37  ┆ null      ┆ TR10      │
│ 5046-419e ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -b288-802 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 442…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ c89cea9d- ┆ VEH_0059  ┆ EMP_004   ┆ RUTA_031 ┆ … ┆ 83.67     ┆ 45877.09  ┆ null      ┆ TR10      │
│ 2d30-4602 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -9a09-830 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 310…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 3afb2886- ┆ VEH_0130  ┆ EMP_005   ┆ RUTA_036 ┆ … ┆ 94.54     ┆ 65191.81  ┆ null      ┆ TR10      │
│ d642-46b3 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -89b6-3bb ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 97f…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0e3dcf2d- ┆ VEH_0027  ┆ EMP_002   ┆ RUTA_030 ┆ … ┆ 89.61     ┆ 7487.87   ┆ null      ┆ T30       │
│ 0bff-4091 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -8ea0-2fa ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ cd6…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [44]:
imposible_speed = data_raw.filter(
    (pl.col("speed") < 0) | (pl.col("speed") > 150)
)
print(f"Dimensions: {imposible_speed.shape}")
imposible_speed.head()

Dimensions: (2000, 15)

shape: (5, 15)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tracking_ ┆ vehicle_i ┆ company_i ┆ route_id ┆ … ┆ battery_l ┆ odometer_ ┆ passenger ┆ event_typ │
│ id        ┆ d         ┆ d         ┆ ---      ┆   ┆ evel      ┆ km        ┆ _count    ┆ e         │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2d505eb6- ┆ VEH_0175  ┆ EMP_005   ┆ RUTA_040 ┆ … ┆ 89.79     ┆ 23073.61  ┆ null      ┆ T30       │
│ 523f-43d7 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -b36b-b8d ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ b86…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ d6806ec3- ┆ VEH_0217  ┆ EMP_002   ┆ RUTA_006 ┆ … ┆ 86.72     ┆ 74085.53  ┆ null      ┆ T30       │
│ 331e-405b ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a0a8-104 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2f5…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 08da269e- ┆ VEH_0178  ┆ EMP_003   ┆ RUTA_002 ┆ … ┆ 96.06     ┆ 29412.8   ┆ null      ┆ TR10      │
│ 6be6-4aa1 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a125-c73 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ b68…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ c816d704- ┆ VEH_0025  ┆ EMP_005   ┆ RUTA_018 ┆ … ┆ 90.0      ┆ 28089.23  ┆ null      ┆ T30       │
│ a6a0-4e34 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -94d8-0a9 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ f25…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ eeb313e2- ┆ VEH_0150  ┆ EMP_005   ┆ RUTA_018 ┆ … ┆ 76.55     ┆ 44855.9   ┆ null      ┆ TR10      │
│ ab76-4854 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -8a49-c6a ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 6fd…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [51]:
MINUTOS_UMBRAL = 5

late_events = (
    data_raw
    .with_columns(
        (pl.col("received_at") - pl.col("event_time")).alias("delay")
    )
    .filter(
        pl.col("delay") > pl.duration(minutes=MINUTOS_UMBRAL)
    )
    .sort("delay", descending=True)
)
print(f"Dimensions: {late_events.shape}")
late_events.head(10)

Dimensions: (7500, 16)

shape: (10, 16)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tracking_ ┆ vehicle_i ┆ company_i ┆ route_id ┆ … ┆ odometer_ ┆ passenger ┆ event_typ ┆ delay     │
│ id        ┆ d         ┆ d         ┆ ---      ┆   ┆ km        ┆ _count    ┆ e         ┆ ---       │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ duration[ │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ f64       ┆ f64       ┆ str       ┆ μs]       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ d6313d28- ┆ VEH_0156  ┆ EMP_001   ┆ RUTA_007 ┆ … ┆ 19953.54  ┆ null      ┆ TR10      ┆ 44m       │
│ 3d6d-404b ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -9b7f-cce ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ f35…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 4bdc4504- ┆ null      ┆ EMP_005   ┆ RUTA_023 ┆ … ┆ 55250.07  ┆ null      ┆ TR10      ┆ 44m       │
│ 1a7d-4692 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -83ba-59a ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 792…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ ba8399e1- ┆ VEH_0218  ┆ EMP_003   ┆ RUTA_028 ┆ … ┆ 46987.08  ┆ null      ┆ TR10      ┆ 44m       │
│ e9c8-458c ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a867-dfd ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ fdd…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 35b3a843- ┆ VEH_0179  ┆ EMP_004   ┆ RUTA_016 ┆ … ┆ 66651.14  ┆ 55.0      ┆ P20       ┆ 44m       │
│ dd0e-48ea ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -b1bd-db5 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 8c0…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 506c3c93- ┆ VEH_0013  ┆ EMP_003   ┆ RUTA_014 ┆ … ┆ 35897.55  ┆ null      ┆ T30       ┆ 44m       │
│ 902e-4e78 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a7b1-bfb ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 95a…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ ace10a03- ┆ VEH_0006  ┆ EMP_001   ┆ RUTA_014 ┆ … ┆ 73009.6   ┆ null      ┆ T30       ┆ 44m       │
│ 2ac9-4f87 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -b760-90b ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 9e1…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ e739c43d- ┆ VEH_0165  ┆ EMP_005   ┆ RUTA_021 ┆ … ┆ 12606.75  ┆ 16.0      ┆ P20       ┆ 44m       │
│ c117-4b2c ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -b548-ce6 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 8c3…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 341e1ac2- ┆ VEH_0205  ┆ EMP_005   ┆ RUTA_004 ┆ … ┆ 74605.99  ┆ null      ┆ T30       ┆ 44m       │
│ e50e-4b00 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -9ed0-c86 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 62a…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ a5895370- ┆ VEH_0026  ┆ EMP_001   ┆ RUTA_011 ┆ … ┆ 40201.18  ┆ null      ┆ TR10      ┆ 44m       │
│ 9fca-4081 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -b0d4-aea ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ efa…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ ffc787d3- ┆ VEH_0105  ┆ EMP_005   ┆ RUTA_038 ┆ … ┆ 77515.02  ┆ null      ┆ TR10      ┆ 44m       │
│ 6c89-497c ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -98b0-c3f ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 304…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [52]:
weak_coverage_zones = (
    late_events
    .with_columns([
        pl.col("latitude").round(3).alias("zone_lat"),
        pl.col("longitude").round(3).alias("zone_lon")
    ])
    .group_by(["zone_lat", "zone_lon"])
    .agg([
        pl.len().alias("total_delayed_events"),
        pl.col("delay").mean().alias("average_delay")
    ])
    .sort("total_delayed_events", descending=True)
)

weak_coverage_zones.head(10)

shape: (10, 4)
┌──────────┬──────────┬──────────────────────┬───────────────┐
│ zone_lat ┆ zone_lon ┆ total_delayed_events ┆ average_delay │
│ ---      ┆ ---      ┆ ---                  ┆ ---           │
│ f64      ┆ f64      ┆ u32                  ┆ duration[μs]  │
╞══════════╪══════════╪══════════════════════╪═══════════════╡
│ 9.852    ┆ -75.516  ┆ 3                    ┆ 31m           │
│ 5.853    ┆ -73.54   ┆ 3                    ┆ 31m           │
│ 7.927    ┆ -75.331  ┆ 3                    ┆ 26m 20s       │
│ 3.035    ┆ -74.114  ┆ 3                    ┆ 33m 20s       │
│ 9.774    ┆ -75.247  ┆ 2                    ┆ 30m 30s       │
│ 6.614    ┆ -74.437  ┆ 2                    ┆ 23m 30s       │
│ 3.534    ┆ -75.908  ┆ 2                    ┆ 25m           │
│ 5.069    ┆ -75.96   ┆ 2                    ┆ 31m           │
│ 6.33     ┆ -73.14   ┆ 2                    ┆ 18m           │
│ 9.46     ┆ -75.089  ┆ 2                    ┆ 28m           │
└──────────┴──────────┴──────────────────────┴───────────────┘

In [46]:
driver_changes = (
    data_raw
    .with_columns(
        pl.col("event_time").dt.date().alias("date")
    )
    .group_by(["vehicle_id", "date"])
    .agg(
        pl.col("driver_id").n_unique().alias("unique_drivers"),
        pl.col("driver_id").unique().alias("drivers_list")
    )
    .filter(pl.col("unique_drivers") > 1)
    .sort(["date", "vehicle_id"])
)

driver_changes.head()

shape: (5, 4)
┌────────────┬──────┬────────────────┬─────────────────────────────────┐
│ vehicle_id ┆ date ┆ unique_drivers ┆ drivers_list                    │
│ ---        ┆ ---  ┆ ---            ┆ ---                             │
│ str        ┆ date ┆ u32            ┆ list[str]                       │
╞════════════╪══════╪════════════════╪═════════════════════════════════╡
│ null       ┆ null ┆ 6              ┆ ["EMP_002_DRV_059", "EMP_003_D… │
│ VEH_0001   ┆ null ┆ 3              ┆ ["EMP_001_DRV_049", "EMP_001_D… │
│ VEH_0003   ┆ null ┆ 3              ┆ ["EMP_003_DRV_048", "EMP_003_D… │
│ VEH_0004   ┆ null ┆ 3              ┆ ["EMP_004_DRV_024", "EMP_004_D… │
│ VEH_0005   ┆ null ┆ 2              ┆ ["EMP_005_DRV_041", "EMP_005_D… │
└────────────┴──────┴────────────────┴─────────────────────────────────┘

In [54]:
odometer_resets = (
    data_raw
    .sort(["vehicle_id", "event_time"])
    .with_columns(
        pl.col("odometer_km").shift(1).over("vehicle_id").alias("previous_odometer")
    )

    .filter(
        (pl.col("odometer_km") < pl.col("previous_odometer")) &
        pl.col("previous_odometer").is_not_null()
    )
    .with_columns(
        (pl.col("previous_odometer") - pl.col("odometer_km")).alias("odometer_drop")
    )
)

print(f"Dimensions: {odometer_resets.shape}")
odometer_resets.head()

Dimensions: (1401, 17)

shape: (5, 17)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tracking_ ┆ vehicle_i ┆ company_i ┆ route_id ┆ … ┆ passenger ┆ event_typ ┆ previous_ ┆ odometer_ │
│ id        ┆ d         ┆ d         ┆ ---      ┆   ┆ _count    ┆ e         ┆ odometer  ┆ drop      │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ f64       ┆ str       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ cc078dfd- ┆ null      ┆ EMP_003   ┆ RUTA_007 ┆ … ┆ null      ┆ T30       ┆ 60843.87  ┆ 40634.16  │
│ 1418-4057 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -b941-4c3 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 679…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ efc6ec3a- ┆ null      ┆ EMP_003   ┆ RUTA_009 ┆ … ┆ null      ┆ TR10      ┆ 49275.68  ┆ 36607.95  │
│ 2524-48b1 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -a4c3-cfe ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 3e2…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 180f2422- ┆ null      ┆ EMP_002   ┆ RUTA_013 ┆ … ┆ null      ┆ TR10      ┆ 12667.73  ┆ 953.84    │
│ 2683-4f8f ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -9e8d-363 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ bbc…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ dafbe468- ┆ null      ┆ EMP_003   ┆ RUTA_017 ┆ … ┆ 11.0      ┆ P20       ┆ 77587.9   ┆ 33593.95  │
│ 0973-44aa ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -af6c-5fb ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 4aa…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 41c9c31a- ┆ null      ┆ EMP_001   ┆ RUTA_033 ┆ … ┆ 5.0       ┆ P20       ┆ 75682.99  ┆ 965.91    │
│ a0e6-4313 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ -bc53-b52 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ fb1…      ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘